apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools-hub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - example.com
      secretName: tools-hub-tls
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tools-hub
                port:
                  number: 80
